### ISSUE TITLE
Critical: 2.2.0 Cannot Start - Bad Naming

### ISSUE THREAD

**Issue by ZAdamMac** [ZAdamMac/Tapestry#38]
**Describe the bug**
The 2.2.0 version is completely invalid as a function is called without ever actually having the name instantiated. How the hell did this pass into release?

**To Reproduce**
1. Install 2.2.0.
2. Run it in any build mode.

**Expected behavior**
The application should run.

**Log/Console Output**
```
Welcome to Tapestry Backup Tool Version 2.2.0
Automatic updates are not currently a function of this script.
Please refer to the repo for updates: https://www.github.com/ZAdamMac/Tapestry
Gathering a list of files to archive - this could take a few minutes.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/patches/.local/lib/python3.8/site-packages/tapestry/__main__.py", line 13, in <module>
    tapestry.runtime()
  File "/home/patches/.local/lib/python3.8/site-packages/tapestry/functions.py", line 1262, in runtime
    do_main(state, gpg_conn)
  File "/home/patches/.local/lib/python3.8/site-packages/tapestry/functions.py", line 334, in do_main
    ops_list = build_ops_list(namespace)
  File "/home/patches/.local/lib/python3.8/site-packages/tapestry/functions.py", line 106, in build_ops_list
    hasher.update(chunk)
NameError: name 'hasher' is not defined
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Version: 2.2.0

**Additional context**

**Comment by ZAdamMac** [comment]
This is resolved with the recent release of 2.2.1 onto pypi.
